name: autolayout

options:
  bundleIdPrefix: dev.jano.injection
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 15.0

settings:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES

targets:

  AutoLayout:
    type: framework
    platform: iOS
    scheme:
      testTargets:
         - InjectionTests
    settings:
       CURRENT_PROJECT_VERSION: 1
       INFOPLIST_FILE: targets/main/Info.plist
       IPHONEOS_DEPLOYMENT_TARGET: 15.0
       PRODUCT_BUNDLE_IDENTIFIER: dev.jano.injection
       PRODUCT_NAME: Injection
    sources: 
       - sources/main
    type: framework

  AutoLayoutTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      INFOPLIST_FILE: targets/tests/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 15.0
      PRODUCT_BUNDLE_IDENTIFIER: dev.jano.injection.tests
      TEST_HOST:
    sources:
      - sources/tests
    dependencies:
      - target: Injection
